/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tusys.view;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import tusys.database.Kuliah;

/**
 *
 * @author nim_13512501
 */
public class jPanelData extends javax.swing.JPanel {

    /**
     * Creates new form jPanelData
     */
    public jPanelData() {
        initComponents();
        buttonGroup1.add(jRadioButtonKuliah);
        buttonGroup1.add(jRadioButtonRuang);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelKuliahdanRuang = new javax.swing.JTable();
        jRadioButtonKuliah = new javax.swing.JRadioButton();
        jRadioButtonRuang = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("TODO Panel Data");

        jTabelKuliahdanRuang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Kuliah", "Nama Kuliah", "Jumlah Peserta", "", ""
            }
        ));
        jScrollPane1.setViewportView(jTabelKuliahdanRuang);

        jRadioButtonKuliah.setText("Data Kuliah");
        jRadioButtonKuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonKuliahActionPerformed(evt);
            }
        });

        jRadioButtonRuang.setText("Data Ruangan");

        jLabel2.setText("Jenis Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addContainerGap(13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButtonKuliah)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonRuang)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonRuang)
                    .addComponent(jRadioButtonKuliah)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showDataKuliah(){
        try {
            Kuliah [] allkuliah = mainMenu.getDbc().getAllKuliah();
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Kode Kuliah");
            model.addColumn("Nama Kuliah");
            model.addColumn("Jumlah Peserta");
            model.addColumn("");
            model.addColumn("");
            
            //aksi hapus
            Action delete = new AbstractAction()
            {
                @Override
                public void actionPerformed(ActionEvent e) {
                    JTable table = (JTable)e.getSource();
                    int modelRow = Integer.valueOf( e.getActionCommand() );
                    JOptionPane.showMessageDialog(null, "operasi hapus belum dibuat");
                }
            };
            //aksi ubah
            Action edit = new AbstractAction()
            {
                @Override
                public void actionPerformed(ActionEvent e) {
                    JTable table = (JTable)e.getSource();
                    int modelRow = Integer.valueOf( e.getActionCommand() );
                    JOptionPane.showMessageDialog(null, "operasi ubah belum dibuat");
                }
            };
            for (int i=0;i<allkuliah.length;i++){
                Object [] r = new Object[5];
                r[0]=allkuliah[i].getKode_kuliah();
                r[1]=allkuliah[i].getNama_kuliah();
                r[2]=allkuliah[i].getJumlah_peserta();
                r[3]="Ubah";
                r[4]="Hapus";
                model.addRow(r);
            }
            jTabelKuliahdanRuang.setModel(model);

            ButtonColumn buttonColumnDelete = new ButtonColumn(jTabelKuliahdanRuang, delete, 4);
            buttonColumnDelete.setMnemonic(KeyEvent.VK_D);

            ButtonColumn buttonColumnEdit = new ButtonColumn(jTabelKuliahdanRuang, edit, 3);
            buttonColumnEdit.setMnemonic(KeyEvent.VK_D);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error" + ex);
            Logger.getLogger(jPanelData.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void jRadioButtonKuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonKuliahActionPerformed
        showDataKuliah();

// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonKuliahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButtonKuliah;
    private javax.swing.JRadioButton jRadioButtonRuang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabelKuliahdanRuang;
    // End of variables declaration//GEN-END:variables

    private MainMenu mainMenu;

    /**
     * @return the mainMenu
     */
    public MainMenu getMainMenu() {
        return mainMenu;
    }

    /**
     * @param mainMenu the mainMenu to set
     */
    public void setMainMenu(MainMenu mainMenu) {
        this.mainMenu = mainMenu;
    }
    
}
